version: "3"
services:
  db:
    image: mongo:latest
    container_name: goatlin_db
    restart: always
    volumes:
      - db:/data/db
    expose:
      - "27017"
  api:
    build: ./packages/services/api
    image: kotlin-scp-api:latest
    container_name: goatlin_api
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
volumes:
  db:
